// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzH0hl5HxY2iVyQNQE_w1Vr9TaY5IQl6g',
    appId: '1:384716873013:web:8e8d94db04b66ac060807c',
    messagingSenderId: '384716873013',
    projectId: 'jaibaan-84699',
    authDomain: 'jaibaan-84699.firebaseapp.com',
    storageBucket: 'jaibaan-84699.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkDN3yRQhvvFstMp0478Y6kA8ZWDJlEmg',
    appId: '1:384716873013:android:f20d1939c0bc82d560807c',
    messagingSenderId: '384716873013',
    projectId: 'jaibaan-84699',
    storageBucket: 'jaibaan-84699.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoM_siPZXxw52K4d2V1SPy4zIneBNVcIQ',
    appId: '1:384716873013:ios:739c7160945e54a160807c',
    messagingSenderId: '384716873013',
    projectId: 'jaibaan-84699',
    storageBucket: 'jaibaan-84699.firebasestorage.app',
    iosBundleId: 'com.example.jaibaan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoM_siPZXxw52K4d2V1SPy4zIneBNVcIQ',
    appId: '1:384716873013:ios:739c7160945e54a160807c',
    messagingSenderId: '384716873013',
    projectId: 'jaibaan-84699',
    storageBucket: 'jaibaan-84699.firebasestorage.app',
    iosBundleId: 'com.example.jaibaan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzH0hl5HxY2iVyQNQE_w1Vr9TaY5IQl6g',
    appId: '1:384716873013:web:bab752f97c47fadf60807c',
    messagingSenderId: '384716873013',
    projectId: 'jaibaan-84699',
    authDomain: 'jaibaan-84699.firebaseapp.com',
    storageBucket: 'jaibaan-84699.firebasestorage.app',
  );
}
